---
name: Unit Tests

on:
  push:
    branches:
      - 'dependabot/*'
      - 'feature-**'
      - 'fix-**'
      - 'main'
      - 'snyk-upgrade-**'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  unit_tests:
    name: Lint and Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2.1.6
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Compile
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm install
      - name: Unit tests
        run: npm test
